#!/bin/sh

./gradlew detekt --auto-correct
if [ $? -ne 0 ]; then
    echo "Detekt нашел неисправимые ошибки. Коммит отменен."
    exit 1
fi

# Проверяем, были ли изменения после автокоррекции
if [ -n "$(git status --porcelain)" ]; then
    echo "Detekt внес изменения, добавляем файлы в коммит..."
    git add -u  # Добавляем измененные файлы в индекс
fi

# Если ошибок нет, завершаем хук успешно
exit 0
