name: Build and Release APK
on:
  push:
    branches:
      - master

jobs:
  build-release:
    if: ${{ startsWith(github.event.head_commit.message, 'v1.') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Verify Commit Message
        run: |
          if [[ ! "${{ github.event.head_commit.message }}" =~ v[0-9]\.[0-9]\.[0-9] ]]; then
          echo "This commit message does not start with '"v*.*.*"'. Skipping."
          exit 1
          fi

      - name: Get Previous Tag
        run: |
          PREVIOUS_TAG=$(git tag --sort=-creatordate | head -n 1) || exit 1
          if [ -z "$PREVIOUS_TAG" ]; then
          echo "No previous tag found, exiting."
          exit 1
          fi
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_ENV

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-wrapper-${{ runner.os }}-

      - name: Setup Java Environment
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1
        with:
          cache: true

      - name: Decode and save keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > keystore.jks
        shell: bash

      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.head_commit.message }}
          body: |
            ## Full Changelog
            https://github.com/vazh2100/GeoEventApplication/compare/${{ env.PREVIOUS_TAG }}...${{ github.event.head_commit.message }}
          files: |
            app/build/outputs/apk/release/com.vazh2100.geoeventapp.${{ github.event.head_commit.message }}.apk